In [1]:
import torch

In [2]:
# each of the values in x is called an element of the tensor
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x.shape

torch.Size([12])

In [4]:
# change the shape ofthe tensor to a matrix X with shape (3, 4)
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [5]:
print(X.reshape(-1, 4))
print(X.reshape(3, -1))

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [6]:
print(torch.zeros(2,3,4))
print(torch.zeros((2,3,4)))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [7]:
print(torch.ones(2,3,4))
print(torch.ones((2,3,4)))
print('*' * 10)
input = torch.empty(2,3)
print(torch.ones_like(input))
print(torch.ones(2,3))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
**********
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


<bold>We often need to initialize the parameters of neural network randomly. This can be done using the torch function randn</bold>

In [8]:
normal_rand = torch.randn(3,4) # normal distribution with a mean 0 and variance 1
uniform_rand = torch.rand(3,4) # uniform distribution on interval [0,1)

print(normal_rand) 
print(uniform_rand) 

tensor([[ 0.6206,  0.7017, -0.1008,  1.8277],
        [ 1.1666,  0.7063, -0.4462,  0.5384],
        [ 0.2560, -0.2874,  0.0073,  0.6566]])
tensor([[0.8109, 0.7101, 0.0220, 0.0625],
        [0.6423, 0.3204, 0.6308, 0.5658],
        [0.4610, 0.9732, 0.9652, 0.3321]])


In [9]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [10]:
print(X)
print(X[-1]) # selects last row
print(X[1:3]) # selects 2nd and 3rd row

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [11]:
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [12]:
X[:2, :] = 4
X

tensor([[ 4.,  4.,  4.,  4.],
        [ 4.,  4.,  4.,  4.],
        [ 8.,  9., 10., 11.]])

In [13]:
X[1:3, 1:3] = 5
X

tensor([[ 4.,  4.,  4.,  4.],
        [ 4.,  5.,  5.,  4.],
        [ 8.,  5.,  5., 11.]])

In [14]:
torch.exp(x)

tensor([5.4598e+01, 5.4598e+01, 5.4598e+01, 5.4598e+01, 5.4598e+01, 1.4841e+02,
        1.4841e+02, 5.4598e+01, 2.9810e+03, 1.4841e+02, 1.4841e+02, 5.9874e+04])

<bold>Scalar function returns one dimensional output given input</bold>

In [15]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

<bold>
dim=0 means vertically (along rows) 
</bold>
<br>
<bold>
dim=1 means horizontally (along columns)
</bold>

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape(3, -1)
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum()

tensor(66.)

### Broadcasting

Under certain conditions, we can still perform elementwise binary operations by invoking the broadcasting mechanism. 
Broadcasting works according to the two step procedure
1. expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape.
2. perform an elementwise operation on the resulting arrays.

In [19]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b, a - b, a * b, a / b

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[ 0, -1],
         [ 1,  0],
         [ 2,  1]]),
 tensor([[0, 0],
         [0, 1],
         [0, 2]]),
 tensor([[nan, 0.],
         [inf, 1.],
         [inf, 2.]]))

### Saving Memory

<bold>Y = X + Y causes the Y to point to newly allocated memory. This is undesirable because we do not want to allocate memory unnecessarily all the time. This causes memory wastage. Whenever possible, we want to perform these updates in place. Secondly, we might point at the same parameters from multiple variables. If we do not update in place, we must be careful to update all of these references, lease we spring a memory leak or inadvertently refer to stale parameters.</bold>

In [21]:
before = id(Y) # saves the Y memory address
Y = X + Y
id(Y) == before

False

In [22]:
Z = torch.zeros_like(Y)
print('id(Z)', id(Z))
Z[:] = X + Y # operation inplace
print('id(Z)', id(Z))

id(Z) 133550077116144
id(Z) 133550077116144


In [23]:
before = id(X)
X += Y
id(X) == before

True

### Tensor to Numpy and Numpy to tensors

In [24]:
xx= torch.tensor([[1,2,3],[4,5,6]])
print(xx.numpy())

[[1 2 3]
 [4 5 6]]


In [29]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [30]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)
# a.item() gives python number from a tensor that has one element

(tensor([3.5000]), 3.5, 3.5, 3)

In [40]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
x,y,x == y,x < y,x > y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))